# Generated by Django 4.1.5 on 2023-02-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_video_file_alter_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.TextField(max_length=200),
        ),
    ]
