# Generated by Django 4.1.5 on 2023-03-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
