# Generated by Django 4.1.5 on 2023-03-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
